server:
  port: 9002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
    register-with-eureka: false #不在注册中心显示
  instance:
    prefer-ip-address: false   #显示真实ip
spring:
  application:
    name: consumer9002
feign:
   hystrix:
       enabled: true
   client:
    config:
      remote-service:           #服务名，填写default为所有服务
        connectTimeout: 3000
        readTimeout: 3000
hystrix:
  command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 3000