server:
  port: 7002
eureka:
  instance:
    hostname: bbb
  client:
    registerWithEureka: false  #是否注册到eureka，不在注册中心显示
    fetch-registry: false  #是否冲eurekaserver获取注册信息
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/