server:
  port: 7001
eureka:
  instance:
    hostname: aaa
  client:
    registerWithEureka: false  #是否注册到eureka
    fetch-registry: false  #是否冲eurekaserver获取注册信息
    serviceUrl:
      defaultZone: http://localhost:7002/eureka/        #多个用逗号间隔