server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
    register-with-eureka: false #不在注册中心显示
  instance:
    prefer-ip-address: false   #显示真实ip
spring:
  application:
    name: consumer9001